### ISSUE TITLE
Feedback style

### ISSUE THREAD

**Issue by roberrrt-s** [RooyyDoe/frontend-data#8]
Hi Roy, Ik heb vrijwel geen feedback, want het ziet er allemaal erg goed uit, ik zou alleen zien dat je je code beter indenteert, want nu zijn er hier en daar wat rare quirks te zien qua hoeveelheid tabs/spaties. Je kunt je code even door een beautifier halen om dat recht te trekken, kijk verder ook nog even naar de consistentie van `() => {}` en `function(d) {}` want die gebruik je nu door elkaar.

```javascript
(d3.hierarchy({children: data})
  .sum(d => d.categoryAmount));
```
Volgens mij hoeven hier geen () omheen.
Veel succes verder

**Comment by RooyyDoe** [comment]
Dankjewel Robert
